### ISSUE TITLE
`margin` noto'g'ri berilgan

### ISSUE THREAD

**Issue by oybek94** [otabek-oktamov/namanganliklar-24-rewiew#2]
`margin-right: auto;` noto'g'ri sababi agar valyutalar kursi o'chib ketadigan bo'lsa  o'ng tomonga taqalib turishi kerak bo'lgan tugmalar logotipni oldiga kelib qoladi.
![Screenshot_1](https://user-images.githubusercontent.com/21256066/115348518-24ef6080-a1cc-11eb-9204-39532460186f.png)

bun to'girlash uchun `header-top-buttons` klassiga `margin-left: auto;` berish kerak shunda tugmalar har doim o`ng tomonga taqalib turadi.
![Screenshot_2](https://user-images.githubusercontent.com/21256066/115348902-a515c600-a1cc-11eb-96c9-71a6216387df.png)

https://github.com/otabek-oktamov/namanganliklar-24-rewiew/blob/0c94a8600ce01ba436e3c082a3ebe48b5e97289e/index.html#L26

**Comment by otabek-oktamov** [comment]
fixed
